name: Validate Binary Compatibility

on:
  workflow_call:
    inputs:
      java:
        type: string
        required: false
        default: 8

jobs:
  cmd:
    name: JDK ${{ inputs.java }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Coursier Cache
        uses: coursier/cache-action@v6.3

      - name: Install Adoptium Temurin OpenJDK
        uses: coursier/setup-action@v1.1.2
        with:
          jvm: adoptium:${{ inputs.java }}

      - name: Binary Compatibility
        run: sbt +mimaReportBinaryIssues
