name: Publish

on:
  workflow_call:
    inputs:
      java:
        type: string
        required: false
        default: 8
    secrets:
      username:
        required: true
      password:
        required: true
      pgp_passphrase:
        required: true
      pgp_secret:
        required: true

jobs:
  cmd:
    name: JDK ${{ inputs.java }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Coursier Cache
        uses: coursier/cache-action@v6.3

      - name: Install Adoptium Temurin OpenJDK
        uses: coursier/setup-action@v1.2.0-M3
        with:
          jvm: adoptium:${{ inputs.java }}

      - name: Publish artifcats
        run: sbt ci-release
        env:
          SONATYPE_USERNAME: ${{ secrets.username }}
          SONATYPE_PASSWORD: ${{ secrets.password }}
          PGP_PASSPHRASE: ${{ secrets.pgp_passphrase }}
          PGP_SECRET: ${{ secrets.pgp_secret }}
