name: SBT command on single Java version

on:
  workflow_call:
    inputs:
      java:
        type: string
        required: false
        default: 8
      scala:
        type: string
        required: false
        default: ""
      cmd:
        type: string
        required: true
      env:
        type: string
        required: false
        default: ""
      cache-key:
        type: string
        required: false
        default: ""
      cache-path:
        type: string
        required: false
        default: ""

jobs:
  cmd:
    name: JDK ${{ inputs.java }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Set ENV variables
        if: inputs.env != ''
        run: echo '${{ inputs.env }}' >> $GITHUB_ENV

      - name: Coursier Cache
        uses: coursier/cache-action@v6.3

      - name: Custom Cache
        uses: actions/cache@v2
        if: ${{ inputs.cache-key != '' && inputs.cache-path != '' }}
        with:
          key: ${{ inputs.cache-key }}
          path: ${{ inputs.cache-path }}

      - name: Install Adoptium Temurin OpenJDK
        uses: coursier/setup-action@v1.2.0-M3
        with:
          jvm: adoptium:${{ inputs.java }}

      - name: Run sbt command
        run: ${{ inputs.cmd }}
        env:
          SCALA_VERSION: ${{ inputs.scala }}

      - name: Cleanup before cache
        shell: bash
        run: |
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
